export const COUNTRY_CODES = [
  { code: '+91', country: 'IN (India)' },
  { code: '+1', country: 'US/CA (North America)' },
  { code: '+44', country: 'UK (United Kingdom)' },
  { code: '+61', country: 'AU (Australia)' },
  { code: '+971', country: 'AE (United Arab Emirates)' },
  { code: '+49', country: 'DE (Germany)' },
  { code: '+33', country: 'FR (France)' },
  { code: '+81', country: 'JP (Japan)' },
  { code: '+86', country: 'CN (China)' },
  { code: '+65', country: 'SG (Singapore)' },
  { code: '+55', country: 'BR (Brazil)' },
  { code: '+27', country: 'ZA (South Africa)' },
  { code: '+7', country: 'RU (Russia)' },
  { code: '+39', country: 'IT (Italy)' },
  { code: '+34', country: 'ES (Spain)' },
  { code: '+82', country: 'KR (South Korea)' },
  { code: '+52', country: 'MX (Mexico)' },
  { code: '+62', country: 'ID (Indonesia)' },
  { code: '+60', country: 'MY (Malaysia)' },
  { code: '+63', country: 'PH (Philippines)' },
  { code: '+64', country: 'NZ (New Zealand)' },
  { code: '+92', country: 'PK (Pakistan)' },
  { code: '+880', country: 'BD (Bangladesh)' },
  { code: '+94', country: 'LK (Sri Lanka)' },
  { code: '+977', country: 'NP (Nepal)' },
  { code: '+31', country: 'NL (Netherlands)' },
  { code: '+41', country: 'CH (Switzerland)' },
  { code: '+46', country: 'SE (Sweden)' },
  { code: '+47', country: 'NO (Norway)' },
  { code: '+45', country: 'DK (Denmark)' },
  { code: '+358', country: 'FI (Finland)' },
  { code: '+43', country: 'AT (Austria)' },
  { code: '+32', country: 'BE (Belgium)' },
  { code: '+353', country: 'IE (Ireland)' },
  { code: '+48', country: 'PL (Poland)' },
  { code: '+90', country: 'TR (Turkey)' },
  { code: '+966', country: 'SA (Saudi Arabia)' },
  { code: '+974', country: 'QA (Qatar)' },
  { code: '+965', country: 'KW (Kuwait)' },
  { code: '+973', country: 'BH (Bahrain)' },
  { code: '+968', country: 'OM (Oman)' },
  { code: '+20', country: 'EG (Egypt)' },
  { code: '+234', country: 'NG (Nigeria)' },
  { code: '+254', country: 'KE (Kenya)' },
  { code: '+54', country: 'AR (Argentina)' },
  { code: '+56', country: 'CL (Chile)' },
  { code: '+57', country: 'CO (Colombia)' },
  { code: '+51', country: 'PE (Peru)' },
];
