export interface Tip {
  id: number;
  title: string;
  description: string;
  image: string;
}

export const tips: Tip[] = [
  { id: 1, title: "The Zeigarnik Effect in UX", description: "People remember uncompleted tasks better than completed ones. Use progress bars to keep users hooked until they finish.", image: "https://picsum.photos/seed/tip1/800/600" },
  { id: 2, title: "Color Psychology: The Trust of Blue", description: "Blue instills security and trust. If you're handling payments or data, subtle blue accents can increase conversion by 15%.", image: "https://picsum.photos/seed/tip2/800/600" },
  { id: 3, title: "Hick's Law of Choice", description: "The time it takes to make a decision increases with the number of choices. Simplify your pricing tiers to exactly 3 options.", image: "https://picsum.photos/seed/tip3/800/600" },
  { id: 4, title: "The Halo Effect", description: "Users judge your entire business by the visual appeal of your hero section. Invest 80% of your design effort above the fold.", image: "https://picsum.photos/seed/tip4/800/600" },
  { id: 5, title: "Fitts's Law for CTAs", description: "Make your 'Buy' buttons larger and place them closer to where the user's thumb or mouse naturally rests.", image: "https://picsum.photos/seed/tip5/800/600" },
  { id: 6, title: "The Scarcity Principle", description: "When something is rare, the brain assigns it higher value. Use limited-time offers to trigger immediate action.", image: "https://picsum.photos/seed/tip6/800/600" },
  { id: 7, title: "Social Proof Validation", description: "We look to others to guide our decisions. A single, specific testimonial is worth 100 generic marketing claims.", image: "https://picsum.photos/seed/tip7/800/600" },
  { id: 8, title: "Anchoring Bias", description: "Always show your most expensive option first. It anchors the user's price expectation, making the middle option look like a steal.", image: "https://picsum.photos/seed/tip8/800/600" },
  { id: 9, title: "The Aesthetic-Usability Effect", description: "Users perceive aesthetically pleasing designs as easier to use, even if they aren't. Beauty hides usability flaws.", image: "https://picsum.photos/seed/tip9/800/600" },
  { id: 10, title: "Von Restorff Effect", description: "The item that stands out is remembered best. Make your primary CTA a contrasting color to the rest of the page.", image: "https://picsum.photos/seed/tip10/800/600" },
  { id: 11, title: "Cognitive Load Reduction", description: "Every extra field in a form decreases conversion by 10%. Only ask for what is absolutely necessary right now.", image: "https://picsum.photos/seed/tip11/800/600" },
  { id: 12, title: "Endowment Effect", description: "People value things more if they feel they own them. Offer free trials so users build attachment to your product.", image: "https://picsum.photos/seed/tip12/800/600" },
  { id: 13, title: "The Reciprocity Norm", description: "Give massive value upfront (like a free guide). The psychological need to return the favor will drive them to buy.", image: "https://picsum.photos/seed/tip13/800/600" },
  { id: 14, title: "Miller's Magic Number", description: "The average person can only hold 7 (plus or minus 2) items in their working memory. Keep menus short.", image: "https://picsum.photos/seed/tip14/800/600" },
  { id: 15, title: "Loss Aversion", description: "The pain of losing is twice as powerful as the pleasure of gaining. Frame your marketing around what they miss out on.", image: "https://picsum.photos/seed/tip15/800/600" },
  { id: 16, title: "Serial Position Effect", description: "Users remember the first and last items in a list best. Put your most important features at the beginning and end.", image: "https://picsum.photos/seed/tip16/800/600" },
  { id: 17, title: "The Paradox of Choice", description: "Too many options cause paralysis. Curate your offerings to guide the user to the best decision quickly.", image: "https://picsum.photos/seed/tip17/800/600" },
  { id: 18, title: "Priming", description: "Subtle visual cues (like an arrow or a person looking in a certain direction) will automatically guide the user's eyes to your CTA.", image: "https://picsum.photos/seed/tip18/800/600" },
  { id: 19, title: "Framing Effect", description: "Saying '90% fat-free' works better than '10% fat'. Frame your statistics to sound overwhelmingly positive.", image: "https://picsum.photos/seed/tip19/800/600" },
  { id: 20, title: "Bandwagon Effect", description: "Highlight how many people are already using your service. 'Join 10,000+ others' triggers a deep tribal instinct.", image: "https://picsum.photos/seed/tip20/800/600" },
  { id: 21, title: "The Goal Gradient Effect", description: "The closer a user gets to a goal, the faster they work to achieve it. Start your onboarding checklist with 2 tasks already checked off.", image: "https://picsum.photos/seed/tip21/800/600" },
  { id: 22, title: "IKEA Effect", description: "When users invest effort into setting up their profile or dashboard, they value the product significantly more.", image: "https://picsum.photos/seed/tip22/800/600" },
  { id: 23, title: "Curse of Knowledge", description: "You know too much about your product. Write your landing page copy for a 12-year-old to ensure absolute clarity.", image: "https://picsum.photos/seed/tip23/800/600" },
  { id: 24, title: "The Peak-End Rule", description: "People judge an experience based on its peak and how it ends. Ensure your checkout success page is highly celebratory.", image: "https://picsum.photos/seed/tip24/800/600" },
  { id: 25, title: "Labor Illusion", description: "If a search takes 2 seconds but shows a 'searching databases' animation, users trust the results more than instant ones.", image: "https://picsum.photos/seed/tip25/800/600" },
  { id: 26, title: "Decoy Effect", description: "Introduce a third pricing option that is slightly inferior to the premium option just to make the premium look like a bargain.", image: "https://picsum.photos/seed/tip26/800/600" },
  { id: 27, title: "Default Effect", description: "People rarely change default settings. Pre-select the pricing plan or option you want them to choose.", image: "https://picsum.photos/seed/tip27/800/600" },
  { id: 28, title: "Gaze Cueing", description: "If you use a photo of a human on your site, ensure their eyes are looking directly at your main headline or button.", image: "https://picsum.photos/seed/tip28/800/600" },
  { id: 29, title: "Bite-Sized Reading", description: "The brain scans before it reads. Use bullet points, bold text, and short paragraphs to make content scannable.", image: "https://picsum.photos/seed/tip29/800/600" },
  { id: 30, title: "Dopamine Hits", description: "Use micro-interactions (like a subtle button pop or confetti on click) to trigger tiny dopamine releases during navigation.", image: "https://picsum.photos/seed/tip30/800/600" },
  { id: 31, title: "The Isolation Effect", description: "Give your most important elements plenty of whitespace. Breathing room forces the brain to focus on what matters.", image: "https://picsum.photos/seed/tip31/800/600" },
  { id: 32, title: "Sensory Language", description: "Use words that invoke the senses ('velvety smooth', 'razor-sharp'). It activates more regions of the reader's brain.", image: "https://picsum.photos/seed/tip32/800/600" },
  { id: 33, title: "Consistency Principle", description: "If you get a user to say 'yes' to a small request (like entering an email), they are 4x more likely to say 'yes' to buying.", image: "https://picsum.photos/seed/tip33/800/600" },
  { id: 34, title: "Friction as a Filter", description: "Adding slight friction (like a mandatory questionnaire) can actually increase the quality of leads and their desire for your service.", image: "https://picsum.photos/seed/tip34/800/600" },
  { id: 35, title: "Visual Hierarchy", description: "The eye naturally reads in an F-pattern or Z-pattern. Place your logo, headline, and CTA along these natural eye paths.", image: "https://picsum.photos/seed/tip35/800/600" },
  { id: 36, title: "The Authority Bias", description: "Displaying logos of companies you've worked with or certifications bypasses the logical brain and instantly builds trust.", image: "https://picsum.photos/seed/tip36/800/600" },
  { id: 37, title: "Storytelling Effect", description: "Facts tell, stories sell. Wrap your product's benefits in a narrative about overcoming a specific struggle.", image: "https://picsum.photos/seed/tip37/800/600" },
  { id: 38, title: "Contrast Principle", description: "Show the 'before' (the painful problem) right next to the 'after' (your glorious solution) for maximum psychological impact.", image: "https://picsum.photos/seed/tip38/800/600" },
  { id: 39, title: "Fear Of Missing Out (FOMO)", description: "Show stock levels ('Only 2 left!') or countdown timers. The primal brain panics at the thought of missing a resource.", image: "https://picsum.photos/seed/tip39/800/600" },
  { id: 40, title: "Zeigarnik in Copywriting", description: "End your emails or paragraphs on a cliffhanger. The brain's need for closure will force them to click through.", image: "https://picsum.photos/seed/tip40/800/600" },
  { id: 41, title: "Familiarity Heuristic", description: "Use standard icons (like a magnifying glass for search). Don't reinvent the wheel if it increases cognitive friction.", image: "https://picsum.photos/seed/tip41/800/600" },
  { id: 42, title: "The Power of Free", description: "The word 'Free' is an emotional hot-button. A 'Free Consultation' always outperforms a 'Strategy Session'.", image: "https://picsum.photos/seed/tip42/800/600" },
  { id: 43, title: "Confirmation Bias", description: "Users come to your site wanting to solve a specific problem. Immediately confirm you understand their exact pain point in the headline.", image: "https://picsum.photos/seed/tip43/800/600" },
  { id: 44, title: "Symmetry and Balance", description: "The brain processes symmetrical designs faster, equating them with stability and professionalism.", image: "https://picsum.photos/seed/tip44/800/600" },
  { id: 45, title: "The Pratfall Effect", description: "Brands that admit a minor flaw (and how they fix it) are perceived as more human and trustworthy than 'perfect' brands.", image: "https://picsum.photos/seed/tip45/800/600" },
  { id: 46, title: "Typography Psychology", description: "Serif fonts feel traditional and reliable. Sans-serif fonts feel modern and innovative. Choose based on your brand identity.", image: "https://picsum.photos/seed/tip46/800/600" },
  { id: 47, title: "Chunking Information", description: "Break long forms or text blocks into small, bite-sized 'chunks'. It prevents the brain from feeling overwhelmed.", image: "https://picsum.photos/seed/tip47/800/600" },
  { id: 48, title: "The Blemishing Effect", description: "Showing a 4.8 star rating actually converts higher than a perfect 5.0 star rating, which the brain perceives as fake.", image: "https://picsum.photos/seed/tip48/800/600" },
  { id: 49, title: "Progressive Disclosure", description: "Only show advanced features or information when the user explicitly asks for it (like an 'Advanced Settings' toggle).", image: "https://picsum.photos/seed/tip49/800/600" },
  { id: 50, title: "The Humor Effect", description: "Information presented with subtle humor is retained significantly longer. Don't be afraid to add a witty error page.", image: "https://picsum.photos/seed/tip50/800/600" }
];
